name       : swh-plugins
version    : 0.4.17
release    : 2
source     :
    - https://github.com/swh/ladspa/archive/v0.4.17.tar.gz : d1b090feec4c5e8f9605334b47faaad72db7cc18fe91d792b9161a9e3b821ce7
license    : GPL-2.0
component  : multimedia.library
summary    : SWH Plugins package for the LADSPA plugin system
description: |
    The SWH Plugins package for the LADSPA plugin system, providing over a hundred plugins
builddeps  :
    - pkgconfig(fftw3f)
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
